name: Workflow Code, Variables, ENV and Secrets

on:
  push:
    branches: [ main ]

jobs:
  Job-Code:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls -la
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls -1

  Job-Variables:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: |
          echo "Variable ACT_VAR_PING says ${{ vars.ACT_VAR_PING }}"
          echo "Variable ACT_VAR_BLUE is actually ${{ vars.ACT_VAR_BLUE }}"

  Job-Env:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "ENV ACT_ENV_HELLO says ${{ env.ACT_ENV_HELLO }}"
          echo "ENV ACT_ENV_I_AM says ${{ env.ACT_ENV_I_AM }}"
      - run: |
          printenv ACT_ENV_HELLO
          printenv ACT_ENV_I_AM

  Job-Secrets:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Secret ACT_SECRET_ONE is (not) top secret anymore:"
          echo ${{ secrets.ACT_SECRET_ONE }} | sed 's/./& /g'
          echo "Secret ACT_SECRET_THREE is (not) top secret anymore:"
          echo ${{ secrets.ACT_SECRET_THREE }} | sed 's/./& /g'
